# Generated by Django 5.1.4 on 2025-02-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sizeandprice_food_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>', max_length=64, unique=True),
        ),
    ]
