# Generated by Django 5.1.4 on 2025-02-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
