# Generated by Django 5.1.4 on 2025-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_foodcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/food_addition'),
        ),
    ]
