# Generated by Django 5.1.4 on 2025-02-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_addition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcondition',
            name='food_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sizeandprice',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Размер'),
        ),
    ]
