# Generated by Django 5.1.4 on 2025-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_discountcondition_food_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='weight',
        ),
        migrations.AddField(
            model_name='sizeandprice',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
