# Generated by Django 5.1.4 on 2025-02-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeandprice',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
